name: List Changed Files

on:
  push:
    branches:
      - main   # Change to your default branch if needed

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changes
        run: |
          git fetch --depth=2
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Upload Changed Files
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: changed_files.txt